---
title: "A Primer on Economic Data Science"
author: "Zhentao Shi"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::pdf_book
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
# github-repo: rstudio/bookdown-demo
description: "nothing"
fontsize: 12pt
geometry: margin=1in
---

# Preface {-}

This course came into being after postgraduate students repeatedly requested for training in coding skills.
Programming is an essential skill for researchers in economic analysis.

I believe the best way to learn programming is via examples. These notes contain many executable  examples that illustrate R usage and econometric computational ideas.


**to be developed**: 

* econometrics is interdisciplinary study involving economics, statistics, operational research, and computational science.
* Reading materials are for peruse. They are not too long. Usually written by experts in the particular topic and offers a big picture. Survey papers, or at least with a survey.
* Open-source attitude. Stand on the shoulder of giants. Do not tend to be comprehensive. Because many topics have excellent writings. We refer to them. Do not reinvent the wheel.


## Personal Reflection {-}

Thirty years ago aspiring young econometricians picked up GAUSS.
Twenty years ago the new blood began with MATLAB.
R raised ten years ago when the time came to my generation.
I have been using R since I started my postgraduate study in Peking University in 2005. 
R helps me with my daily research and teaching.

There are other candidates in statistical programming, for example Matlab, Python, Julia and Fortran.
Each language has its own pros and cons.
R has many advantages.
First, it inherits the standard program syntax from C. It is quick to learn for anyone with prior programming experience.
Moreover, once you master R, it is easy to switch to other language, if not R, in your workplace in the future.

Second, backed by a vast statistician community, R enjoys a large selection of packages, including the most recent ones.
When they publish a paper, often times statisticians write and upload a companion R package to facilitate user adoption.

Third, R is free.
It was the primary reason that I chose it at the very beginning.
In the era of cloud computing, an algorithm written in R is easier to share, test, and improve.
Anyone can run R code on any platform, free of license and fee headache.

R is not without limitations. For example, speed is a concern when running big and complex jobs.
However, it will not be an issue in the problems that we will encounter in the first-year postgraduate study.

Lastly, learning a language is a non-trivial investment of our precious time.
It is much more important to master one language with fluency than to know several languages.

R is not the only language available for computing. Why not Python? 
Python is a general purpose language, not a scientific computing language. 
We need to import external modules even for basic numerical operations.
For example, I personally don't like `np.mean`, `np.var` and `np.log`, and its index from 0.
For basic matrix manipulation, the default behavior of `numpy` is different from R.

Why not Julia? Julia is too young to have a big community. 
We would wait until it grows into more stable status. 
Moreover, the speed advantage does not help much in interactive usage in empirical research.

Over the years, I have had a taste of both Python and Julia. 
In my opinion, R so far best suits our purpose of learning a computing language for statistics and econometric analysis.

## Prerequisite {-}

For this course, please install [R](http://www.r-project.org/) or  [Microsoft Open R](https://mran.microsoft.com/open).
An fully functional integrated development environment (IDE) is also highly desirable.
It makes programming user-friendly and enjoyable.
[RStudio](http://www.rstudio.com/) is recommended.

## Structure {-}

The book version can be partitioned into three parts: R, Econometrics, and Machine Learning.


## Packages {-}

```{r,eval=FALSE}
install.packages(c("plyr", "foreach", "doParallel", 
                   "sampleSelection", "AER", "mcmc", "randomForest"))
```
