---
title: "Computational Methods in Economics"
author: "Zhentao Shi"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::pdf_book
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "nothing"
fontsize: 11pt
---
# Preface {-}

This course came into being after postgraduate students repeatedly requested for training in coding skills.
Programming is an essential skill for researchers in economic analysis.

I believe the best way to learn programming is via examples. This book contains many examples that illustrate R usage and econometric computational ideas.

## Personal Reflection {-}

Thirty years ago apsiring young econometricians picked up GAUSS.
Twenty years ago the new blood began with MATLAB.
R raised ten years ago when the time came to my generation.
I have been using R since I started my postgraduate study in Peking University in 2005. R helps me with my daily research and teaching.

There are other candidates in statistical programming, for example Matlab, Python, Julia and Fortran.
Each language has its own pros and cons.
R has many advantages.
First, it inherits the standard program syntax from C. It is quick to learn for anyone with prior programming experience.
Moreover, once you master R, it is easy to switch to other language, if not R, in your workplace in the future.

Second, backed by a vast statistician community, R enjoys a large selection of packages, including the most recent ones.
When they publish a paper, often times statisticians write and upload a companion R package to facilitate other researchers' adoption.

Third, R is free.
It was the primary reason that I chose it at the very beginning.
In the era of open-source software, an algorithm written in R is easier to share, test, and improve.
Anyone can run R code on any platform, free of license and fee headache.

R is not without limitations. For example, speed is a concern when running big and complex jobs.
However, it will not be an issue in the problems that we will encounter in the first year postgraduate study.

Lastly, learning a language is not a trivial investment.
It is much more important to master one language than to know several or many languages.

## Prerequisite {-}

For this course, please install [R](http://www.r-project.org/) or  [Microsoft Open R](https://mran.microsoft.com/open).
An fully functional integrated development environment (IDE) is also highly desirable.
It makes programming user-friendly and enjoyable.
[RStudio](http://www.rstudio.com/) is recommended.

## About Book Version {-}

I prepare the lecture notes in Rmarkdown.
The book version can be built in RStudio.
