---
title: "Premilinary Example of Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: bootstrap
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
load("big150.Rdata")
library(ggplot2)
library(reshape2)

big150_1 = big150[, c("typb", "b1", "b1_c")]

big150_1 = melt(big150_1, id.vars = "typb", measure.vars = c("b1", "b1_c"))
names(big150_1)[2] = c("estimator")


p1 = ggplot(big150_1)
p1 = p1 + geom_area(stat = "density", alpha = .25,
                    aes(x = value, fill = estimator),  position = "identity")
p1 = p1 + facet_grid( . ~ typb )  
p1 = p1 + geom_vline(xintercept = 0)
p1 = p1 + theme_bw()
p1 = p1 + theme(strip.text = element_text( size = 12),
                axis.text = element_text( size = 12))

p1_ly = ggplotly(p1)
p1_ly

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
library(lattice)
library(ggplot2)
library(reshape2)

load("multigraph.Rdata") # load data


# unify the theme in the two graphs
theme1 = theme_bw() + theme(axis.title.x = element_blank(),
                            strip.text = element_text( size = 12),
                            axis.text = element_text( size = 12),
                            legend.position = "bottom", legend.title = element_blank())

# sug-graph 2
d2$month = 1:480
p2 = ggplot(d2)
p2 = p2 + geom_line(  aes(x = month, y = value, col = variable) )  
p2 = p2 + theme1 +  ylab("price and fundamental")

p2_ly = ggplotly(p2)
p2_ly

```
